name: CI-unix

on:
  pull_request:
    paths:
      - '**'
      - '!docs/**'
      - '!src/win/**'
      - '!.**'
      - '.github/workflows/CI-unix.yml'
  push:
    branches:
      - v[0-9].*
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: configure
        run: |
          ./autogen.sh
          mkdir build
          (cd build && ../configure)
      - name: distcheck
        run: |
          make -C build distcheck

  build-android:
    runs-on: ubuntu-latest
    container: reactnativecommunity/react-native-android:v15.0
    env:
      ANDROID_AVD_HOME: /root/.android/avd
      MIN_ADK: 24
    steps:
      - uses: actions/checkout@v4
      - name: Envinfo
        run: npx envinfo
      - name: Install Android ABI arm64-v8a
        run: |
          # TODO: This can be in a pre-built docker image
          # Android-30 is the first to support running Arm64 binaries after Emulator 28 removed support for Arm64 systems
          sudo apt update
          sudo apt install qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
          sdkmanager "emulator" "system-images;android-30;google_apis;x86_64"

      - name: Start emulator
        run: |
          echo no | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64"

          adb start-server

          emulator @test -memory 2048 -no-audio -no-window -gpu off -no-snapshot -no-boot-anim -netdelay none -netspeed full -no-snapshot-save -no-snapshot-load -writable-system  &

          adb wait-for-device

          adb shell "su 0 setenforce 0" # to allow some syscalls like link, chmod, etc.

          # Push the build and test fixtures to the device
          adb push build /data/local/tmp
          adb shell mkdir /data/local/tmp/build/test
          adb push test/fixtures /data/local/tmp/build/test

      - name: Test
        run: |
          adb shell "cd /data/local/tmp/build ; env UV_TEST_TIMEOUT_MULTIPLIER=5 ./uv_run_tests_a"
